[package]
name = "mrcp_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
tungstenite = "0.20"
futures-util = "0.3"
url = "2"
serde_json = "1"
hyper = { version = "0.14", features = ["full"] }
mime_guess = "2.0"
